#cloud-config
users:
    - name: user1
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      shell: /bin/bash
      ssh-authorized-keys:
          - "ssh-rsa key1"
runcmd:
    - "ansible-pull --url https://github.com/megaeee/genotek-ansible main.yaml \
        -e githubuser=user \
        -e githubpassword=password \
        -e yctoken=token \
        -e yccloudid=cloid_id \
        -e ycfolderid=folder_id \
        -e expid=experiment_id"

output:
    init:
        output: "> /var/log/cloud-init.out"
        error: "> /var/log/cloud-init.err"
    config:
        output: "> /var/log/cloud-config.out"
        error: "> /var/log/cloud-config.err"
    final:
        output: "> /var/log/cloud-final.out"
        error: "> /var/log/cloud-final.err"
